### ISSUE TITLE
setForeignState if value is from type object

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/adapter-core#190]
@AlCalzone 

As discussed in Telegram, here is the issue.

If I have a value of type object, then the value is not written when using the function `await this.setForeignStateAsync(id, value, true);`

If I use `await this.setForeignStateAsync(id, {val: value, ack: true});` instead, the value is written

With js-controller 2.2.9 no error message is generated.

As discussed I test it with 3.x. Report me then again

**Comment by AlCalzone** [comment]
This does not seem to be an issue, since in the reported case, `value` does not have an object type.
