### ISSUE TITLE
Async functions (promisifed versions) are not known by adapter-core

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/adapter-core#2]
e.g. getStateAsync

**Comment by AlCalzone** [comment]
Is this still an issue? 
Should be fixed by
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31742
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31836
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31855

**Comment by foxriver76** [comment]
Is working fine ;-)
