### ISSUE TITLE
Property 'from' does not exist on type 'Object'.

### ISSUE THREAD

**Issue by DutchmanNL** [ioBroker/adapter-core#204]
but it exist on every object, issue happens in onObjectChange(){}
<img width="681" alt="Schermafbeelding 2020-04-04 om 14 21 00" src="https://user-images.githubusercontent.com/7318445/78450536-84410800-767f-11ea-82e5-20fec9dc07e0.png">

**Comment by AlCalzone** [comment]
fixed in the latest version

**Comment by DutchmanNL** [comment]
confirmed
