### ISSUE TITLE
Missing smartName in TypeScript definition

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/adapter-core#251]
The iot adapter (and possibly others) uses the `common.smartName` property to know how the state should be named e.g. in Alexa.

`smartName` can be `'ignore'` (special case: the state is to be ignored), a simple string or an object containing at least:
```
{
  byOn: boolean;
  en: string;
}
```
It is very much possible that there are more properties in the object.
You can find more infos here:
https://github.com/ioBroker/ioBroker.iot/blob/master/lib/alexaSmartHomeV2.js

**Comment by AlCalzone** [comment]
Fixed in `@types/iobroker@3.0.12`
