### ISSUE TITLE
step and chart is missing in type definitions, info is missing in documentation

### ISSUE THREAD

**Issue by gaudes** [ioBroker/adapter-core#283]
Hi,

step is defined as a common attribute for states in schema:

common.step (optional) - increase/decrease interval. E.g. 0.5 for thermostat

See https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/dev/objectsschema.md

Also chart is defined as object type in schema, but not included in definition:

chart - charts

Please integrate in type definitions.

"info" is defined as object in definitions, but missing in schema.md.

Please fix definitions or documentation :)

Thanks and regards,

Ralf

**Comment by AlCalzone** [comment]
fixed
