### ISSUE TITLE
getStates pattern might be more than just a string

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/adapter-core#284]
https://github.com/ioBroker/ioBroker.socketio/blob/523a681cffc77847286cad5c274f038559f26718/example/conn.js#L1196
https://github.com/ioBroker/ioBroker.socketio/blob/523a681cffc77847286cad5c274f038559f26718/example/conn.js#L645

**Comment by foxriver76** [comment]
Types are now handled in controller.
