### ISSUE TITLE
Offer decrypt method directly on adapter-code import

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/adapter-core#319]
Should we offer the "tools.decrypt" directly on the adapter-core import object? Else it is needed to include tools ... 

Ok normally noone should use/need it ... but ...

**Comment by AlCalzone** [comment]
Is this still relevant?
https://github.com/ioBroker/ioBroker.js-controller/blob/535d01d04ab9e05a7af08c0e0428f5d57bbca882/lib/adapter.js#L7826-L7846

**Comment by Apollon77** [comment]
Yes ...  we could think to remive in controller 4 ... but I have no idea how many adapters would need to be adjusted then ...

**Comment by Apollon77** [comment]
Close, we have in adapter
