### ISSUE TITLE
Think about adding some kind of "Docker detection"

### ISSUE THREAD

**Issue by buanet** [ioBroker/adapter-core#331]
It might be useful to let adapters know that they are running inside a Docker container. There are some special things coming up when running ioBroker inside a Container. 

Just some example use cases:

1. Running an adapter which uses multicast > if its working or not depends on the network configuration of the container > developer can add a hint and maybe a link for additional information at the adapter settings page
2. Backitup adapter > restoring only works when iobroker is stopped > it would be possible to add a docker specific start/ stop script to the adapter to get restore working in docker
3. Running yahka or z-wave adapter > adapters need some special settings (environment variables) in docker > developer can add a hint and maybe a link for additional information at the adapter settings page

How to determine if something is running inside a Docker container is shown here for example: 
https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker

Cases 3 may also need a detection if the docker image is the official ioBroker docker image because the environment variables are defined within the image.
For this kind of detection it may work if I place some kind of identification file inside the docker image. 

Any thoughts to this? 

Regards,
André

**Comment by Apollon77** [comment]
I like the idea.
For sure to get an "easy way to detect our own container" is awesome. Additionally we should also support other containers and add an other generic way f detection.

I would provide that as a method from adapter-core

**Comment by Apollon77** [comment]
isDocker method from js-controller tools will be exposed by adapter-core 2.6.8, see #408
