### ISSUE TITLE
Update all dependencies and release 2.4.1

### ISSUE THREAD

**Issue by UncleSamSwiss** [ioBroker/adapter-core#332]
When I tried to do an `npm update` inside an adapter directory, it wouldn't update `@types/iobroker`.

Thus we should release a new version with all latest dependencies, even if we don't have any new features.

**Comment by Apollon77** [comment]
there is a 2.4.1 in the meantime

**Comment by AlCalzone** [comment]
Dependabot now increases the versions in package.json when it does an update. New version coming soon.

**Comment by AlCalzone** [comment]
> there is a 2.4.1 in the meantime

There isn't. It was just a PR by Bluefox.

**Comment by AlCalzone** [comment]
2.5.0 is on the way. The `devDependencies` are up to date in the package-lock.json and will be bumped in `package.json` the next time dependabot does an update. `@types/iobroker` is now on the latest `3.3.0`.
