### ISSUE TITLE
Exposing controller tools install/uninstall npm and isDocker

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/adapter-core#408]
expose https://github.com/ioBroker/ioBroker.js-controller/blob/fafabd20af76b3cae124318c8af3d3826d2979c3/packages/common/lib/common/tools.js#L3468-L3469 

will close #https://github.com/ioBroker/ioBroker.js-controller/issues/202

**Comment by foxriver76** [comment]
Do we need to expose more than install/uninstall @Apollon77?

**Comment by Apollon77** [comment]
It seems only this is left

**Comment by Apollon77** [comment]
And we should also add isDocker

**Comment by Apollon77** [comment]
Hm ... overseen this ... @AlCalzone @foxriver76 I think we said we need to do the "installNodeModule" differently, right= SO I would not expose them right now ... but maybe do isDocker?

**Comment by foxriver76** [comment]
We can expose it if needed won’t hurt imo

**Comment by Apollon77** [comment]
@foxriver76 @AlCalzone Please review of both commits, then I do a 2.6.8

**Comment by foxriver76** [comment]
> @foxriver76 @AlCalzone Please review of both commits, then I do a 2.6.8

LGTM

**Comment by AlCalzone** [comment]
Fine with the `isDocker` thing.
Not sure if we want to make the `npm install` stuff globally available before we've decided on https://github.com/ioBroker/ioBroker.js-controller/issues/2006

**Comment by foxriver76** [comment]
node modules will be handled via https://github.com/ioBroker/ioBroker.js-controller/pull/2650/files
