### ISSUE TITLE
Typing issues

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/adapter-core#455]
- [x] `findObjectCallback` - according to types, name is string but it should be `stringOrTranslated`
- [ ] `Object/AnyObject` always has a type, however this is not true for the `_design/xy` objects, they have no type but have property `views` e.g.
```
{
  "_id": "_design/chart",
  "language": "javascript",
  "views": {
    "chart": {
      "map": "function(doc) { if (doc.type === 'chart') emit(doc._id, doc); }"
    }
  },
  "from": "system.host.ubuntu.cli",
  "ts": 1644561649221,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

- [x] `RmResult` and thus `RmCallback` states there is a property `isDir`, code-wise it is never there.
- [x] `ReadDirResult` states, that property `stats` is of type `fs.Stats`, sometimes objects db just returns an empty object, I assume that `Partial<fs.Stats>` would be a better fit
- [x] `ReadFileCallback`/`ReadFilePromise` declare a property `file` but the property is called `data` code-wise
- [ ] `StateCommon` can basically have `[other: string]`, or at least https://github.com/ioBroker/ioBroker.js-controller/blob/86e3a2e82e535713b07691b7cf4cd22f8119bcf1/packages/db-objects-redis/src/lib/objects/objectsInRedisClient.js#L51
We should discuss this in https://github.com/ioBroker/ioBroker.js-controller/issues/507
- [x] On `ReadFilePromise`, `mimeType` can be `undefined`
- [ ] we should extend types of `ReadDirCallback` to ensure that the result is defined, if error is falsy, because code-wise it is
- [x] `StringOrTranslated` proeprty `en` should not be optional if it is an object
- [x] `UnloadHandler` states that there is always the argument `callback` however, we check if arg is there, else we `await` it because we assume it to return a promise
- [ ] Adapter.js sets `binary: boolean` on `StateObject` if it corresponding to a binary object.
- [ ] `InstanceCommon` can have `restartSchedule: string` (schedule)
- [ ] `InstanceCommon` can have property `wakeup` boolean
- [ ] `InstanceCommon` can have `version` string or maybe better type possible for semver
- [ ] In general we should check if `InstanceCommon` is not mainly a copy of `AdapterCommon`
- [ ] `SetStateChangedCallback` make `err` optional like on `setStateCallback`
- [ ] same for `GetStateCallback`, `GetStatesCallback`
- [ ] `delBinaryState` returns optional id as second CB parameter and is not a normal `ErrorCallback`
- [ ] `AdapterCommon` can have `news` as i18n object
- [ ] `InstanceCommon` has property `logLevel` but it should be `loglevel`
- [ ] `AdapterObject` can have `dependencies` and `globalDependencies`

**Comment by AlCalzone** [comment]
@foxriver76 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60350 solves some of these.

**Comment by foxriver76** [comment]
I will further extend the list in initial post with findings of adapter.js/ts

**Comment by AlCalzone** [comment]
> * `MessagePayload` is `any` according to @Apollon77

Really? Is there not a more specific type that does not turn off all checking?

**Comment by Apollon77** [comment]
The "message" is send to the adapter, so the content of the message field is kind of defined by the receiver ... it could be "nothing" aka undefined or null or any other data including string, number, array. object, boolean ....

**Comment by foxriver76** [comment]
Types are now handled in controller.
