### ISSUE TITLE
start in compact mode no longer possible

### ISSUE THREAD

**Issue by Sneak-L8** [ioBroker/adapter-core#581]
When stating ke-contact Adapter in compact mode, I'm getting the error "Cannot start kecontact.0 in compact mode. Fallback to normal start: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.kecontact/node_modules/@iobroker/adapter-core/build/index.js'"
as suggested by @Apollon77 this issue is opened.
eMail-Adapter (1.2.2) still runs fine with compact mode.

**Comment by Sneak-L8** [comment]
I don't think so. There was only one commit for this adapter.  Four days ago I updated TR-064 adapter (fritzbox) and got same  error. After disabling compact mode, error was gone.

**Comment by foxriver76** [comment]
I guess this all works again with controller 6.0.11?

**Comment by Sneak-L8** [comment]
Just checked. I put TR-064 and kecontact in compact mode. Both are starting without errors. So it seems it's fixed.
Tested on Controller 6.0.11

**Comment by foxriver76** [comment]
Thanks for the super quick reply
